### ISSUE TITLE
Enumerate all dor-services consumers needing update to 5.x

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#136]
Much of the work has been done in Argo.  This is essentially a compounded maintenance burden, including dor-services-app and all robots.  Most, if not all of these are still on ruby 1.9, so there is more than `bundle update` to do.

Repos:
_Robots_
- [x] https://github.com/sul-dlss/assembly/issues/19 -- [PR](https://github.com/sul-dlss/assembly/pull/22)
- [x] https://github.com/sul-dlss/was-seed-preassembly/issues/5 -- [PR](https://github.com/sul-dlss/was-seed-preassembly/pull/8)
- [x] https://github.com/sul-dlss/was-seed-dissemination/issues/3 -- [PR](https://github.com/sul-dlss/was-seed-dissemination/pull/4)
- [x] https://github.com/sul-dlss/was-crawl-preassembly/issues/17 -- [PR](https://github.com/sul-dlss/was-crawl-preassembly/pull/18)
- [x] https://github.com/sul-dlss/was-crawl-dissemination/issues/17 -- [PR](https://github.com/sul-dlss/was-crawl-dissemination/pull/18)
- [x] https://github.com/sul-dlss/was-dissemination/issues/2 -- [PR](https://github.com/sul-dlss/was-dissemination/pull/3)
- [x] https://github.com/sul-dlss/common-accessioning/issues/39 -- [PR](https://github.com/sul-dlss/common-accessioning/pull/40)
- [x] https://github.com/sul-dlss/gis-robot-suite/issues/83 -- [PR](https://github.com/sul-dlss/gis-robot-suite/pull/84)
- [x] https://github.com/sul-dlss/sdr-preservation-core
- [x] https://github.com/sul-dlss/robot-master/issues/58 -- [PR](https://github.com/sul-dlss/robot-master/pull/60)
- [x] https://github.com/sul-dlss/robot-suite-base/issues/7 -- [PR](https://github.com/sul-dlss/robot-suite-base/pull/8)
- [x] https://github.com/sul-dlss/item-release/issues/34 -- [PR](https://github.com/sul-dlss/item-release/pull/35)

Derelicts:
- [ ] https://github.com/sul-dlss/etd-robots/issues/1 on a `2.2` version!
- [ ] https://github.com/sul-dlss/eems-robots 
- [ ] https://github.com/sul-dlss/hydra_etd/issues/3
- [ ] https://github.com/sul-dlss/hydrus/issues/25 -- has separate solr, update not needed.
- [ ] https://github.com/sul-dlss/dor-utils/issues/7 - not testable, arguably only useful as example code
- [ ] workflow-archiver -- uses `lyber-core` ([Gemfile](https://github.com/sul-dlss/workflow-archiver/blob/master/workflow-archiver.gemspec#L19)) but seemingly only hits `dor_service_uri + "/dor/v1/objects/#{druid}/versions/current"`

We probably should ignore the above group as they are either not remotely updatable or run isolated from the dor/argo index.  

_Other_
- [x] https://github.com/sul-dlss/dor-services-app/issues/12
- [ ] https://github.com/sul-dlss/dor-fetcher-service/issues/32 -- [PR](https://github.com/sul-dlss/dor-fetcher-service/pull/36)
- [ ] https://github.com/sul-dlss/purl-fetcher-app/issues/1 -- split off from dor-fetcher-service
- [x] https://github.com/sul-dlss/lyber-core/issues/10 -- [gemspec](https://github.com/sul-dlss/lyber-core/blob/master/lyber-core.gemspec)
- [x] https://github.com/sul-dlss/pre-assembly/issues/6 -- [PR](https://github.com/sul-dlss/pre-assembly/pull/10)
- [x] https://github.com/sul-dlss/assembly-utils/issues/7 --  [PR](https://github.com/sul-dlss/assembly-utils/pull/8)
- [x] https://github.com/sul-dlss/editstore-updater/tree/master  - master branch already updated, just needs to be deployed and tested (currently deployed version is `master-rails3` branch)
- [x] https://github.com/sul-dlss/etd_model/issues/4 -- [PR](https://github.com/sul-dlss/etd_model/pull/6)
- [x] https://github.com/sul-dlss/oai-provider (defunct)
- [x] https://github.com/sul-dlss/geohydra (defunct)
- [x] https://github.com/cbeer/dor_to_fcrepo4 (experimental)
- [ ] ???

**Comment by drh-stanford** [comment]
Also https://github.com/sul-dlss/item-release/blob/master/Gemfile#L4

**Comment by atz** [comment]
And many other projects use lyber-core...

**Comment by jmartin-sul** [comment]
here are the results of the dor-services usage survey i sent out over the summer...

client application | respondent/maintainer | dor-services vers | overall usage | concerns | notes
---------------------- | ------------------------------ | ----------------------- | ------------------ | ------------ | -------
gis-robot-suite | @drh-stanford | 4.21.4 | item.find, reading datastreams, tagging |  | doesn't use Solr functionality directly, but solrizer.url is in the config and points to argo's index
robot-master | @drh-stanford | 4.21.2 | search and workflow service calls.  Issues issue specific Solr queries (e.g. objectType_t:workflow). | will need to update Solr queries | 
dor-utils | @drh-stanford | 4.21.0 | uses dor-services for a variety of service calls | |
editstore-updater | @peetucket | 4.21.2 | "web app with background processing" | "does not interact with solr directly to my knowledge, only via the gem itself" | 
pre-assembly | @peetucket | 4.21.4 | "command line ruby app" | "does not interact with solr directly to my knowledge, only via the gem itself" | 
assembly-utils | @peetucket | 4.19.x | gem | "may have some solr interactions, but probably not important...this gem is still used and required in multiple projects, but the methods invoked are limited" | 
dor-fetcher-service | @peetucket & carrick | n/a | web service app | "no dor-services, but direct querying of argo solr (read only) -- fields queried are configurable, so may just require configuration changes" | 
assembly (robots) | @peetucket | 4.21.4 |  | "does not interact with solr directly to my knowledge, only via the gem itself" | 
dor-services-app | @tingulfsen | 4.21.2 |  |  | 
etd | @tallenaz | 2.2.4 |  | "I don't know the dor-services gem well enough to say off the top of my head what they use it for, but I can look into it." | "has it's own ancient version of solr"
etd-robots | @tallenaz | 2.2.2.1 |  |  |  
Was-Crawl-Preassembly-WF | Ahmed | 4.21.4 | "Query/Update DOR Items and Collections, and Workflow-services" | _Q:_ Is dor-services used to interact with Solr, or to create Solr documents from repository objects?  _A:_ "No. Generally, the rest of my apps are using the dor-service-app to register objects."
Was-Crawl-Dissemination-WF | Ahmed | 4.21.4 | "Query/Update DOR Items and Collections, and Workflow-services" | _Q:_ Is dor-services used to interact with Solr, or to create Solr documents from repository objects?  _A:_ "No. Generally, the rest of my apps are using the dor-service-app to register objects."
Was-Seed-Preassembly-WF | Ahmed | 4.21.4 | "Query/Update DOR Items and Collections, and Workflow-services" | _Q:_ Is dor-services used to interact with Solr, or to create Solr documents from repository objects?  _A:_ "No. Generally, the rest of my apps are using the dor-service-app to register objects."
Was-Seed-Dissemination-WF | Ahmed | 4.21.4 | "Query/Update DOR Items and Collections, and Workflow-services" | _Q:_ Is dor-services used to interact with Solr, or to create Solr documents from repository objects?  _A:_ "No. Generally, the rest of my apps are using the dor-service-app to register objects."
Was-Dissemination-WF | Ahmed | 4.21.4 | "Query/Update DOR Items and Collections, and Workflow-services" | _Q:_ Is dor-services used to interact with Solr, or to create Solr documents from repository objects?  _A:_ "No. Generally, the rest of my apps are using the dor-service-app to register objects."

**Comment by rosy1280** [comment]
*Robots*

Note: generally the robots should be easy to upgrade, presuming: 
* the robots follow the new workflow framework that was released a year ago (robots master)
* the methods they use to transform content are still present in the gem

Robots that may cause problems
* EEMs (really out of date)
* ETDs (really out of date)
* sdr-preservation-core (hasn't been updated in quite some time)
* item-release (lots of dependencies)

It may be best to upgrade and push the robot suites to stage and just exercise them manually (ie have @blalbrit [assembly, accession], @drh-stanford [gis] and nicholas [was] @rosy1280 [pc] accession content)

**Comment by tallenaz** [comment]
eems-robots are now at https://github.com/sul-dlss/eems-robots

**Comment by jmartin-sul** [comment]
if you're updating solr field names in your application, here's a set of grep statements that i used on argo to find solr field names in the old schema style, which pretty much uses entirely different suffixes from the field names in the new style.  it definitely found some false positives, but it was really helpful for figuring out what needed updating.

```bash
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_facet[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_t[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_s[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_display[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_dt[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_sim[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_field[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_date[\'\", ]" .
grep -r --exclude="*/argo-master-bugfix/*" --include="*.rb" --include="*.erb*" "_datetime[\'\", ]" .
```

more history on field conversion can be found on the ARGO-406 issue in SUL's jira instance.  i can note that stuff over here if people end up needing more context to be more immediately available on this github issue.

**Comment by darrenleeweber** [comment]
There is no dependency on `dor-services` in sul-dlss/sdr-preservation-core, either in the Gemfile or in the results of `bundle show --paths`, i.e.
```
$ bundle show --paths | grep 'dor'
/home/dlweber/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/dor-workflow-service-1.8.0
$ grep 'dor' Gemfile
gem 'dor-workflow-service', '~> 1.8'
```
So, ticking off the checkbox at the top of this issue (wondering why it was identified in the first place).

**Comment by atz** [comment]
@darrenleeweber: the transitive dependencies (through lyber-core) still need to be examined and confirmed to be compatible.

**Comment by darrenleeweber** [comment]
@atz - so if all the specs in lyber-core are passing, is that sufficient for anything using lyber-core?  All the specs in sdr-preservation-core are working with the lyber-core version noted above.  So, I presume that the API exposed by lyber-core and used by SDR-PC is working as expected.  Is there an update to lyber-core to evaluate for SDR-PC?

**Comment by atz** [comment]
@darrenleeweber: no, since the consumers of lyber-core could have version-dependent code.  Notably, so far I haven't found any such consumers that don't also include dor-services directly.

**Comment by atz** [comment]
Condensation of @jmartin-sul's greps for efficiency:
```
egrep -r --include="*.rb" --include="*.erb*" -e "_(facet|t|s|display|dt|field|date|datetime)[\'\", ]" .
```

**Comment by drh-stanford** [comment]
I can do `gis-robot-suite`, `robot-master`, and `robot-suite-base`.

**Comment by drh-stanford** [comment]
I didn't see this in the discussion but we also need to upgrade to ruby 2.x for anything that use `dor-workflow-service`, right?

**Comment by jmartin-sul** [comment]
useful regexps when looking for fedora datastream manipulation:
`\.[A-Za-z]\+Metadata.*=`
`content_will_change`

another useful string to look for when searching for Solr usage is `Solrizer.solr_name` (since solrizer behavior may have changed between the versions used in dor-services 4 and dor-services 5, and some of the calls to solrizer may have changed as the schema was refined).

**Comment by drh-stanford** [comment]
robot-master is completed and it requires ruby 2.x upgrades on the lyberservices VMs.

**Comment by drh-stanford** [comment]
gis-robot-master is completed and it already has ruby 2.x in the kurma VMs

**Comment by atz** [comment]
Calling this one done.
